{
 "title": "Logs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Action Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (record_extra_action) (count_over_time({service_name=\"log-generator\"} | json | logfmt [$__range]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=`log-generator`} | json | logfmt | drop __error__, __error_details__"
    }
   ]
  },
  {
   "title": "Logs by level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (detected_level) (count_over_time({service_name=\"log-generator\"} | json | logfmt [$__range]))"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=`log-generator`} | detected_level=`error` | json | logfmt | drop __error__, __error_details__"
    }
   ]
  }
 ]
}