apiVersion: 1
datasources:
  - name: Loki
    uid: ee19h0cttekg0b
    type: loki
    editable: true
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      timeout: 60
      maxLines: 1000