receivers:
  filelog:
    include:
      - /app/logs/file_*.log
    start_at: end
    operators:
      - type: json_parser

processors:
  resource:
    attributes:
      - action: insert
        key: service.name
        value: log-generator
      - action: insert
        key: loki.format
        value: json

#  transform:
#    error_mode: ignore
#    log_statements:
#        - context: log
#          statements:
#            - set(attributes["name_of_the_service"], attributes["record"]["extra"]["service"])

exporters:
  otlphttp:
    endpoint: http://loki:3100/otlp
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [resource]
      exporters: [otlphttp, debug]